### ISSUE TITLE
Non-existing filter values cause 500

### ISSUE THREAD

**Issue by goapunk** [liqd/adhocracy4#1073]
**URL:** https://aplus-dev.liqd.net/julian-test/projects/module/debatte-17/?ordering=thisCausesA500
**user:** any
**expected behaviour:** show page with default filter?
**behaviour:** throws 500
**important screensize:**
**device & browser:** 
**Comment/Question:**  Happens with the ordering filter, probably with others too

Screenshot?

**Comment by Rineee** [comment]
fixed
