### ISSUE TITLE
poll: multiple choice with other choice option broken

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy4#1103]
**URL:** https://aplus-dev.liqd.net/liqd-tests/projects/module/umfrage-31/ or https://meinberlin-stage.liqd.net/projekte/running-poll-with-content/
**user:** 
**expected behaviour:** 
**behaviour:** in a multiple choice (where I can choose more than one option) with other option, when I first click other and enter my text and then after that also click another option afterwards, the text I entered in other is gone
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
also changing multiple choice answers broken

**Comment by phillimorland** [comment]
related https://github.com/liqd/adhocracy-plus/issues/2239
