### ISSUE TITLE
Unclear relation with liquid democracy

### ISSUE THREAD

**Issue by Chealer** [liqd/adhocracy4#1160]
adhocracy4 is being developed by Liquid Democracy e.V and is presented as a successor to [liqd/adhocracy](https://github.com/liqd/adhocracy). One could therefore assume that adhocracy4 aims to implement liquid governance... yet, based on what I understand from ticket #300, it may not.

Unfortunately, its documentation does not clarify the question. The README or some other document should treat the functional differences with adhocracy, or explicitly indicate adhocracy4's relation with liquid democracy.

By the way, the README's last paragraph currently has a half-broken link to a+ (due to an error in Markdown syntax).

**Comment by rittermo** [comment]
Hi @Chealer, thanks for your isssue! Could you elaborate/link to more info what you mean by Liquid Governance? I assume you are talking about delegated voting? That, indeed, is not part of adhocracy4 at this point. However, there is much more than delegated voting to the concept of Liquid Democracy as we (and other organizations focussed more on the deliberative aspects of it). You can read more about our understanding of the concept [on our website.](https://liqd.net/en/academy/vision-und-konzept-von-liquid-democracy/)

**Comment by Chealer** [comment]
Hi @rittermo and thank you very much for your quick feedback,

> Hi @Chealer, thanks for your isssue! Could you elaborate/link to more info what you mean by Liquid Governance?

By "liquid governance", I mean a generalization of liquid democracy, whether it is used in a democracy, in an oligarchy, a meritocracy, a corporation or any other organization.


> I assume you are talking about delegated voting? 

I am afraid that liquid governance is not a precise concept, but yes, I am talking about efficient governance enabling metadelegation.


> That, indeed, is not part of adhocracy4 at this point.

Thank you


> However, there is much more than delegated voting to the concept of Liquid Democracy as we (and other organizations focussed more on the deliberative aspects of it) understand it. You can read more about our understanding of the concept [on our website.](https://liqd.net/en/academy/vision-und-konzept-von-liquid-democracy/)

Thank you. To clarify, I have no doubt that adhocracy enables relatively efficient governance, but I am not shopping for a governance engine at this time. All I was trying to do was to document engines which enable liquid governance, and I was not sure whether adhocracy should be included in the (currently extremely short) list. By the way, if adhocracy4 was to support liquid governance at some point, I would be most pleased to include it in the list if someone lets me know.

**Comment by rittermo** [comment]
@Chealer Thank you for your answer! It’s true that there are very few actively developed software projects implementing delegated voting mechanisms, but having an overview over the few projects that do implement is beneficial nonetheless. Good luck with your research!

**Comment by goapunk** [comment]
I'm closing this as resolved (?)

**Comment by Chealer** [comment]
@goapunk: can you clarify how this was resolved?
