### ISSUE TITLE
Comment Report: Modals with form do not have error handling

### ISSUE THREAD

**Issue by khamui** [liqd/adhocracy4#1346]
**URL:** 
**user:** 
**expected behaviour:** Modals with form should show validation errors
**behaviour:** Modals with form do not have any validation errors
**important screensize:**
**device & browser:** 
**Comment/Question:** 
This error was mentioned here: https://github.com/liqd/adhocracy4/pull/1338#discussion_r1093364758

As the Report Modal inherits the base Modal, it misses validation errors as well. See related issue here:
https://github.com/liqd/adhocracy4/issues/1149

**Comment by TeaJayyy** [comment]
Modals with forms (report) have a character limit but its not displayed and no error message when trying to send. Maybe make send button inactive when form is empty?

**Comment by CarolingerSeilchenspringer** [comment]
@TeaJayyy @mcastro-lqd Will close this issue as we have a design task for this and the design is currently in coordination with client.
