### ISSUE TITLE
Make install not working at the moment

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy4#137]
error occurs when installing requirements

**Comment by xi** [comment]
Can you provide the error message?

I recently head the following message, maybe its the same for you:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted
```

This first occurred after an OS upgrade. Starting with a fresh virtualenv solved the issue for me.

**Comment by MagdaN** [comment]
Oh sorry, this Issue is in the wrong repository
