### ISSUE TITLE
a4-comments: unify textarea character counter for simpler screen reader handling

### ISSUE THREAD

**Issue by hom3mad3** [liqd/adhocracy4#1581]
The meinBerlin redesign simplified the textarea character counter to display as `0/4000`. However, this differs from the library's current format `0/4000 Characters`, leading to a convoluted and overly complex solution. 
In order to maintain clean code practices, we propose standardizing the character counter on all platforms to either display "0/400" or stick to "0/400 Characters". This makes sure we stay consistent and also simplifies the code by focusing on a singular solution everywhere.

the issue has been introduced in https://github.com/liqd/adhocracy4/commit/61855b37cc5bcc82eeb110ac39c718dd84e179d3

![meinBerlin-a4-comments](https://github.com/liqd/adhocracy4/assets/8156337/e0201a51-3b0f-4965-85c6-db5aefe1d926)

**Comment by CarolingerSeilchenspringer** [comment]
@hom3mad3 I think we can quickly decide on this: I prefer 0/4000 characters (in German 0/4000 Zeichen) as it makes more clear what it means. This is also what we currently have for the comments on both a+ and mB. @TeaJayyy @mcastro-lqd do you have a different opinion? @mcastro-lqd do we have restrictions here coming from Berlin styleguide?
