### ISSUE TITLE
Not possible to sort TimeStampedModel by modified

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy4#218]
`TimeStampedModel.modified` is `None` if the item has never been modified. This makes sense, especially considering UI where edited items get an additional "this has been edited on …" label.

However, this makes it impossible to sort by "recent changes". It might be better to set both `modified` and `created` on creation. To know weather an item has been edited you would then check for equality of these fields.

**Comment by fuzzylogic2000** [comment]
Not currently needed, can be refactored in case it is
