### ISSUE TITLE
Investigate cache backends (possibly redis)

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy4#246]
Wagtail recommends to use redis for caching purposes. It supports various caching mechanisms like caching parts of views, sessions etc. It looks like by enabling redis, we can heavily speed up our sites without much effort.

Related links:
- http://niwinz.github.io/django-redis/latest/
- http://django-redis-cache.readthedocs.io/en/latest/intro_quick_start.html
- https://www.revsys.com/blog/2015/may/06/django-performance-simple-things/
- http://docs.wagtail.io/en/latest/advanced_topics/performance.html
- http://michal.karzynski.pl/blog/2013/07/14/using-redis-as-django-session-store-and-cache-backend/

**Comment by fuzzylogic2000** [comment]
@goapunk Do we have a story for this? Or some other place to document what we tried so far? I think this should be moved there.

**Comment by goapunk** [comment]
@fuzzylogic2000 there's a story for performance improvements for mB, but not for a4
