### ISSUE TITLE
Invalid form submit should return appropriate http status code

### ISSUE THREAD

**Issue by ihucos** [liqd/adhocracy4#260]
If for example I fill the form of the face to face module wrongly and submit (with inspect element remove the browser validation before), the http status code is 200

In which other places that happens must be investigated.

This is relevant for example in testing, where I can check by the http status code if the form validation was successfully.

See the screenshot:
![screenshot from 2018-05-08 18-32-01](https://user-images.githubusercontent.com/2066372/39770431-4bbfdfa2-52ef-11e8-916b-93c9096a2f58.png)

But most important of all:
I already spend so much time looking for a paint program for linux, how can i draw red circles on an image? Gimp is completely overkill for this.

**Comment by fuzzylogic2000** [comment]
I think we do the validation of the dashboard in the browser, so I don't know what to do about that.

Inkscape would be the paint-thingy to draw perfect circles or stars or whatever with!

**Comment by ihucos** [comment]
> Inkscape would be the paint-thingy to draw perfect circles or stars or whatever with!
yeah, I'll try that!!

I'll see if I find a quick fix for the pr I am working with and close since, I think its a bug but in a not perfect world it's a technical nuance, so i'll close it.

**Comment by ihucos** [comment]
Naaahh, changing this would look ugly, i thought doing the vanilla django way would raise a non 200 status code but that seems not to be the case. The code is great
