### ISSUE TITLE
IntegrityError in ratings

### ISSUE THREAD

**Issue by treba123** [liqd/adhocracy4#293]
See:
- https://sentry.liqd.net/sentry/debattenportalspdde/issues/84/
- https://sentry.liqd.net/sentry/meinberlin-prod/issues/5/

**Comment by MagdaN** [comment]
I believe that happens when users have the same page open in different tabs and try to rate in one tab even though they already rated in the other tab and did not refresh the page

**Comment by treba123** [comment]
Alright, I'll check that. If that's the cause, I'll try to add a check for that.

**Comment by treba123** [comment]
> I believe that happens when users have the same page open in different tabs and try to rate in one tab even though they already rated in the other tab and did not refresh the page

Confirmed. But it only happens if the user didn't rate the comment (or whatever it is) before. So I guess the offending function might be https://github.com/liqd/adhocracy4/blob/44b104bbeff2400e62f5e9033cd217ec7757d493/adhocracy4/ratings/api.py#L26
