### ISSUE TITLE
IGBCE - difficulty navigating back from user profile

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy4#494]
**behaviour:** when i have not contributed to any participation and I am in profile settings or profile view, the only way to navigate back to my organisation is to click on a+ logo which is not very intuitive

**Comment by fuzzylogic2000** [comment]
and it only works on redirected sites. (Where the landing page redirects to the organisation page)

**Comment by phillimorland** [comment]
@fuzzy, ignore these, I added to a4 not a+, was wondering where they went, will move them now
