### ISSUE TITLE
Remove meinberlin specific code related to embedding

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy4#59]
#53 adds code that is specific for embedding in meinberlin. This feature is currently in a test phase. After the test phase, there are two options:

- Remove the code from this repository and find a way to do embedding in meinberlin without changes to core (e.g. by defaulting to the "external" embed target.)
- Move the embedding feature (most importantly documentation) to core.

Future pull requests that contain similar changes should reference this issue so we can keep track.

**Comment by fuzzylogic2000** [comment]
Only part of the old comments, which we will remove anyway.
