### ISSUE TITLE
reporting for users not logged in does not work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy4#625]
**URL:** in semi-public project https://aplus-dev.liqd.net/liqd-tests/projects/testing-semi-public-projects/ but also in public project https://aplus-dev.liqd.net/liqd-tests/projects/debatte-test/
**user:** not logged in
**expected behaviour:** I can report critical comments
**behaviour:** I can open the report form but the send button does not react
**important screensize:**
**device & browser:** safari on Mac
**Comment/Question:** I think we should allow unregistered users to report, even though otherwise they can't participate. If they should not be able to, we should not show report-button. 

Screenshot?
![Bildschirmfoto 2020-11-04 um 17 19 43](https://user-images.githubusercontent.com/35491681/98137401-3a90f800-1ec2-11eb-8db7-151f148640b8.png)

**Comment by rmader** [comment]
The code is in a4, moving the issue.
