### ISSUE TITLE
Improvements to Maps

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy4#64]
- [x] make attribution configurable
- [ ] validate GeoJSON (in GeoJSON field)
- ~~rethink if we actually want GeoJSON, or store Points and MultiPolygons in Leaftlet representation~~
  - we want to stick to GeoJSON (decided in Scrum of Scrums)
  - was only an option to simplify validation
- [x] document `isMarkerInsidePolygon` algorithm properly
- [x] replace view mixins for list and detail with template tag to use in detail and list view
- [x] rename display_points attribute from point to points
- [x] don't use map_url and base_url as synonyms
- [x] prefix all settings value with A4 or A4_MAPS
- [ ] set a better default help text for `GeoJSONField`
- [ ] do not hardcode height
   - add as optional parameter to template tag and widget, with old value as default, and none if None
- [ ] consistent usage of form controls in different templatetags/widgets (display_points currently uses a custom solution)
- [ ] Show rates in pins only if the rating feature is enabled

**Comment by fuzzylogic2000** [comment]
partly done
