### ISSUE TITLE
Comments: case semi-public and not-invited-member

### ISSUE THREAD

**Issue by khamui** [liqd/adhocracy4#707]
Reviewing the flags `isContextMember` and `isReadOnly` for the case semi-public and not-invited-member to show the right message in the comment section.

**Comment by fuzzylogic2000** [comment]
Copy of @Rineee s explanation of the isContextMember:

> You can find the definition here: https://github.com/liqd/adhocracy4/blob/fba25b7d8b2341de541592849ad0ba7295c25614/adhocracy4/comments_async/templatetags/react_comments_async.py#L74-L75

> The NormalUser is a dummy user defined here: https://github.com/liqd/adhocracy4/blob/master/adhocracy4/rules/discovery.py

> So altogether isContextMember is true if the project is public (coming from the NormalUser part, because for public projects any authenticated user is context member) or the user is authenticated and is participant/moderator/org_member.

> I hope this helped and wasnt even more confusing :grimacing: 

So, now we only also need to state a bit more clearer what isReadOnly means...

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @sabinammm When testing the comments in mB, could you also please test the case of a semi-public project? If it makes sense, what we show to unauthenticated users, and to users that are not participants, i.e. can only view the comments, but not comment. During and after phase. And if that is all fine, please close this issue.
