### ISSUE TITLE
async serializer: also set is_deleted to True for blocked comments

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy4#899]
**URL:** 
**user:** 
**expected behaviour:** readable code, comments should have distinctive properties with distinct names, meanings and behavior
**behaviour:** **Async comments** have the properties `is_removed` and `is_deleted`. Comments that are either removed (by a moderator) or deleted (by a creator) are both set to `is_deleted` and their content is permanently deleted.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Because the serializer does not differentiate between moderator and creator for deleting the comment, does it actually make sense to show this differentiation in the serializer?
This is related to #902 and #903
Screenshot?

**Comment by fuzzylogic2000** [comment]
is_removed is an actual model field, like is_censored and is_blocked. 
is_deleted is added in the serializer. We use it to determine if we show the ratingBox:
https://github.com/liqd/adhocracy4/search?q=is_deleted
So, that means that we probably also set is_deleted True for is_blocked. You shoudn't be able to rate on blocked comments.
https://github.com/liqd/adhocracy4/blob/635d2a3a2c5c487b5538af4c7d6c255c65b92d5d/adhocracy4/comments_async/serializers.py#L113

**Comment by fuzzylogic2000** [comment]
Steps to fix:
1. check in kosmo that blocked comments can be rated on. (Is this bug real?)
2. in the serializer: make is_deleted also depend on is_blocked
3. check that it is fine in kosmo
