### ISSUE TITLE
Refactor redundant comment properties is_blocked, is_censored

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy4#902]
**URL:** 
**user:** 
**expected behaviour:** readable code, comments should have distinctive properties with distinct names, meanings and behavior
**behaviour:** **Async comments** have the properties `is_blocked` and `is_censored`. Comments that are either blocked or censored by a moderator are both no longer visible. YET, while censored comments are set to `is_deleted` and their content is permanently deleted, blocked comments are only not shown, are not set to` is_deleted`, and they can be unblocked if necessary.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
How is `is_censored` actually used? Is it still necessary or should it be removed?
This issue is related to #899 and #903

Screenshot?

**Comment by fuzzylogic2000** [comment]
As we discussed, Is_censored is used when a comment is deleted by a moderator (in the frontend). As we change that behaviour with the is_blocked, wher comments can be unblocked (and we thus need to keep the text), we need both.
