### ISSUE TITLE
Refactor unused(, redundant) comment property is_moderator_marked

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy4#903]
**URL:** 
**user:** 
**expected behaviour:** readable code, comments should have distinctive properties with distinct names, meanings and behavior
**behaviour:** **Async comments** have the property `is_moderator_marked` (default value False) in addition to other properties pertaining to moderation, but `is_moderator_marked` is never set to True regardless of other moderation actions. It seems to be unused and thus redundant to the other properties.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Can we get rid of this property?
This issue is related to #899 and #902 

Screenshot?

**Comment by fuzzylogic2000** [comment]
we use it for comments that should be shown at the top of lists, by using that field for the ordering filter.
