### ISSUE TITLE
refactor blocktrans blocks

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy4#920]
**URL:** 
**user:** 
**expected behaviour:** Translations in po-files in the projects from blocktrans blocks contain linebreaks with \n in them, if they are not in 1 line in the templates, i.e. they need to close on the same line that they are openend on.
**behaviour:** 
These cases were found in a4-meinBerlin in templates from a4:
https://github.com/liqd/adhocracy4/blob/e03fe5a065c08d29b075f004b58f713e61557169/adhocracy4/categories/templates/a4categories/includes/module_categories_form.html#L3

https://github.com/liqd/adhocracy4/blob/e03fe5a065c08d29b075f004b58f713e61557169/adhocracy4/images/templates/a4images/image_upload_widget.html#L19

https://github.com/liqd/adhocracy4/blob/e03fe5a065c08d29b075f004b58f713e61557169/adhocracy4/labels/templates/a4labels/includes/module_labels_form.html#L3

**important screensize:**
**device & browser:** 
**Comment/Question:** 
Check if there are others and refactor as was done https://github.com/liqd/a4-meinberlin/pull/4055
Screenshot?

**Comment by fuzzylogic2000** [comment]
I would not change it here as the changed translations would affect all projects and would also have to be changed on transifex in multiple languages. So, let's keep it like that for now and change it when we touch it anyway. (So, reviewing and writing code remember to check if there are multiple-line blocktrans tags.)
