### ISSUE TITLE
refactor project and module predicates

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy4#927]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** We currently have two places to check predicated depending on items. Most are separately added in the modules predicates, using the projects predicate, but with the project from the item:
for initiators: https://github.com/liqd/adhocracy4/blob/4dbbd6f7c2d882295c92f2c51a08650f78f131fd/adhocracy4/modules/predicates.py#L16
for moderators: https://github.com/liqd/adhocracy4/blob/4dbbd6f7c2d882295c92f2c51a08650f78f131fd/adhocracy4/modules/predicates.py#L23
and also if the project (and thus the item) is live: https://github.com/liqd/adhocracy4/blob/4dbbd6f7c2d882295c92f2c51a08650f78f131fd/adhocracy4/modules/predicates.py#L53

Only for project group members, we check in the project predicates for both cases, when we get the project or the item:
https://github.com/liqd/adhocracy4/blob/4dbbd6f7c2d882295c92f2c51a08650f78f131fd/adhocracy4/projects/predicates.py#L7

**important screensize:**
**device & browser:** 
**Comment/Question:** While I find both methods make sense, I would like to only do it ONE way.
Either check both in the project predicates (checking if we already have the project and otherwise getting it) 
or check the predicates relying on projects in the project predicates and then add them again in the module predicates and use them to check if the project of the item has the predicate.

I think, I slightly prefer the latter as it is more explicit (not checking `hasattr(subject, 'project')` to find out, if we already have the project or sth. else) and it would only mean refactoring one predicate. :)
@Rineee @sabinammm Which one do you prefer?

**Comment by Rineee** [comment]
@fuzzylogic2000 I also prefer the latter! I think it is more explicit than testing if its a item by checking hasattr(subject, 'project'). So go for it! :)
