### ISSUE TITLE
comments: make sure blocked comments are not searched or filtered for their category

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy4#978]
**URL:** 
**user:** 
**expected behaviour:** when I search for sth. in the comments, I do not expect to find blocked comments, of which I cannot see the comment text
**behaviour:** because the search happens in the backend, blocked comments are also searched, while the comment list from the serializer does not show the comment text of searched comments
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
Hahahaha :see_no_evil:

**Comment by fuzzylogic2000** [comment]
Ok, it is the same for the category filter. :grimacing:
